### ISSUE TITLE
Drop down menu to select schools on registerWithSchool

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#184]
**Please describe what has to be done**
On the registerWithSchool page, we currently have a text box that allows the user to type in their school name. We should make this a drop-down menu instead.

**Comment by schans2** [comment]
There are a lot of schools out there. Unless we only want to start with a few schools, I think we should keep the text box and also have a dropdown under it. The dropdown could then narrow down as the user types, referencing some database of school names. Hope that makes sense, tell me what you think.

**Comment by hbh7** [comment]
Yeah so basically make it a search box dropdown hybrid thing, I would definitely be on board with that. 

Since we'll have only 1 school (at least to start, but maybe for a long time idk), it may be nice to have the dropdown always visible so that the user doesn't have to type if there's literally only `<=  height of box `options.

**Comment by hbh7** [comment]
Oh another thing I just thought of, I think we will want school-based login as well. Doesn't do much good if we can only use the school login once and then you're out of luck lol. We'll probably want to talk about this at the next meeting but I'll go and create an issue for it.

**Comment by hbh7** [comment]
Complete in #216
