### ISSUE TITLE
autofill security code

### ISSUE THREAD

**Issue by neha-deshpande001** [PollBuddy/PollBuddy#185]
**Please describe what has to be done**
In the resetPassword page, autofill the security code that we sent to their email.

**Comment by hbh7** [comment]
Probably the best way to go about this would be to have a url parameter and
just read that into the box programatically.

Ex: email has url of pollbuddy.app/resetPassword?resetcode=abc123
Code abc123 gets read by frontend and displayed in box.

**Comment by hbh7** [comment]
Not super important until the backend can even generate and send such codes, so this is now on hold.

**Comment by hbh7** [comment]
Taking off hold as it'd be a decent first issue since we've already got code in the frontend that can pull a URL parameter like that. It'd just be copying the existing code and having it look for a different name. The backend part should be a separate issue already so hopefully that gets done at some point, but isn't a requirement for now at least.

**Comment by hbh7** [comment]
Done in #491
