### ISSUE TITLE
Account info page functionality, visual design

### ISSUE THREAD

**Issue by hbh7** [PollBuddy/PollBuddy#274]
**Please describe what has to be done**

- [x] Currently there's repeated fields at the bottom. They probably just need to be removed (although it's possible the bottom one is preferred and should be integrated, see code compared to other pages)
- [x] Current password/confirm password should be indicated as not required to enter unless you want to change it
- [x] Current/Confirm password should follow password placeholder visuals (see #246)
- [x] Should submit a request to the backend to make changes
- [x] Some sort of confirmation message
- [x] Loading wheel while data is gathered for prepopulating fields
- [x] Prepopulating fields
- [x] Some indication of login type (Poll Buddy or school)
- [x] Bounce to /login if user is not logged in

**Comment by annieshi6** [comment]
duplicated fields already removed, password placeholders should also be fixed (might need to push) in page-fix

**Comment by hbh7** [comment]
Added todo item: Bounce to /login if user is not logged in

**Comment by gangus1** [comment]
I created some mockups of what I had in mind for the account information page. I'm dropping them here instead of in a separate issue since this directly correlates. 

Something similar to this

![Group 1](https://user-images.githubusercontent.com/49348508/109561440-28f3e180-7aab-11eb-9e88-1ed437f416b0.png)

With a separate page for changing passwords.

![Group 1(1)](https://user-images.githubusercontent.com/49348508/109561446-2a250e80-7aab-11eb-9201-962ae9ddac44.png)

Let me know if you have any thoughts or some additions to make to this.

One thing I am thinking of just now as I am posting this is a Forgot Password button. I am unsure how that is currently handled but if it needs to be handled here that is another addition.

**Comment by hbh7** [comment]
Lots of progress in #510

**Comment by hbh7** [comment]
One more todo

**Comment by hbh7** [comment]
Done in #627
